spring.application.name=coffeebara
server.port=18080
spring.profiles.active=local
spring.sql.init.mode=always

kakao.local.base-url=https://dapi.kakao.com
app.search-cache.ttl-seconds=10
mybatis.mapper-locations=classpath:/mapper/*.xml
